CREATE SCHEMA IF NOT EXISTS faculty;
CREATE TABLE faculty.students (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 surname varchar(100) NOT NULL, first_name varchar(100) NOT NULL,
 patronymic varchar(100), birth_date date NOT NULL,
 email varchar(254) NOT NULL UNIQUE
);
CREATE TABLE faculty.student_addresses (
 student_id bigint PRIMARY KEY REFERENCES faculty.students(id) ON DELETE CASCADE,
 city varchar(100) NOT NULL, street varchar(150) NOT NULL, house varchar(20) NOT NULL
);
CREATE TABLE faculty.student_phones (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 student_id bigint NOT NULL REFERENCES faculty.students(id) ON DELETE CASCADE,
 phone_number varchar(30) NOT NULL, UNIQUE(student_id, phone_number)
);
